### ISSUE TITLE
Error: No such file or directory @ rb_sysopen

### ISSUE THREAD

**Issue by yumitsu** [Homebrew/homebrew-livecheck#48]
I tapped it yesterday, used `brew livecheck` a few times - it showed a lot of errors during usage.
Today I tried to use it again:
```
$ brew livecheck
Error: No such file or directory @ rb_sysopen - /Users/yumitsu/.brew_livecheck_watchlist
```
After that I untapped repo, did `brew update` and tapped it again, but with same result.
```
$ brew livecheck -d
Error: No such file or directory @ rb_sysopen - /Users/yumitsu/.brew_livecheck_watchlist
/usr/local/Homebrew/Library/Homebrew/brew.rb:107:in `exit'
/usr/local/Homebrew/Library/Homebrew/brew.rb:107:in `<main>'
```

**Comment by yumitsu** [comment]
Was fixed with `touch ~/.brew_livecheck_watchlist`.
